
package ch.fhnw.ds.ws.graph.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GraphServiceImplService", targetNamespace = "http://server.graph.ws.ds.fhnw.ch/", wsdlLocation = "http://localhost:9877/graph?wsdl")
public class GraphServiceImplService
    extends Service
{

    private final static URL GRAPHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GRAPHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GRAPHSERVICEIMPLSERVICE_QNAME = new QName("http://server.graph.ws.ds.fhnw.ch/", "GraphServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9877/graph?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GRAPHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GRAPHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GraphServiceImplService() {
        super(__getWsdlLocation(), GRAPHSERVICEIMPLSERVICE_QNAME);
    }

    public GraphServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GRAPHSERVICEIMPLSERVICE_QNAME, features);
    }

    public GraphServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GRAPHSERVICEIMPLSERVICE_QNAME);
    }

    public GraphServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GRAPHSERVICEIMPLSERVICE_QNAME, features);
    }

    public GraphServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GraphServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GraphServiceImpl
     */
    @WebEndpoint(name = "GraphServiceImplPort")
    public GraphServiceImpl getGraphServiceImplPort() {
        return super.getPort(new QName("http://server.graph.ws.ds.fhnw.ch/", "GraphServiceImplPort"), GraphServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GraphServiceImpl
     */
    @WebEndpoint(name = "GraphServiceImplPort")
    public GraphServiceImpl getGraphServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.graph.ws.ds.fhnw.ch/", "GraphServiceImplPort"), GraphServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GRAPHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GRAPHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GRAPHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
